apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-ng-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-ng
  targetCPUUtilizationPercentage: 70
status:
  currentReplicas: 1
  desiredReplicas: 2
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: back-ng-hpa
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: back-ng
  targetCPUUtilizationPercentage: 70
status:
  currentReplicas: 1
  desiredReplicas: 2
