apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: back-ng
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: front-ng
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer