apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: arbaazij/backend_t
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
               name: my-env-secrets  # Load all environment variables from the Secret
